#!/bin/bash
sudo apt-get install fish
curl -L https://get.oh-my.fish | fish
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
sudo apt-get install fonts-powerline
omf install bobthefish
sudo apt install python3-dev python3-pip
sudo pip3 install thefuck

sudo add-apt-repository ppa:qos/pulseaudio-dlna
sudo apt install pulseaudio-dnla
